### ISSUE TITLE
Améliorer les modalités de contact de l'équipe terrain

### ISSUE THREAD

**Issue by christianroy** [a10s-ca/referentiel#10]
Soit une adresse courriel commune

Ou un formulaire de contact (voir https://stackoverflow.com/questions/24348223/send-email-from-static-page-hosted-on-github-pages pour des pistes)

**Comment by v-cao** [comment]
Ce serait : info@datascene.ca

**Comment by v-cao** [comment]
Fait ? À moins qu'on ne laisse ouvert, si on veut faire un vrai formulaire de contact.

**Comment by christianroy** [comment]
Hmmm... je pense que le formulaire serait joli, mais beaucoup d'efforts pour peu de contacts! Je suggère ceci:

* je vais créer une vraie page "contact" avec les noms des membres du comité et l'adresse info
* la page Contribuer sera donc plus petite avec seulement la mention actuelle et une lien vers la page de contact

Une fois que ce sera fait je vais fermer la présente issue.

**Comment by christianroy** [comment]
c'est fait!
