### ISSUE TITLE
Mesure de visites (Analytics)

### ISSUE THREAD

**Issue by christianroy** [a10s-ca/referentiel#7]
* Configurer et ajouter Google Tag Manager
* Configurer et ajouter Google Analytics
* Ajouter un outil de "cookie consent"

**Comment by v-cao** [comment]
On pourrait se trouver un moment pour le faire !

**Comment by christianroy** [comment]
> On pourrait se trouver un moment pour le faire !

yep, c'est sur ma todolist! Je pense que ça devrait venir avec des conditions d'utilisation / politique de confidentialité minimales, parce qu'à partir de là nous allons collecter des données (anonymes). Il me semble que tu avais peut-être du matériel de ton côté?

**Comment by christianroy** [comment]
@v-cao Je viens de déployer le staging avec Analytics configuré et un cookie consent: https://referentiel-staging.netlify.app/ J'en ai profité pour corriger deux coquilles et mettre l'adresse info@datascene.ca dans la page pour contribuer au référentiel, en attendant de faire un vrai formulaire de contact.

Si tout te convient (pas essentiel de montrer à tout le comité je crois!), je dépoie en prod et confirme que les données Analytics se compile, puis je partagerai l'accès au compte à tout le monde.

**Comment by v-cao** [comment]
Ça me va, testons en production !

**Comment by christianroy** [comment]
C'est déployé et je confirme que ça fonctionne!
